language: generic
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.8
    packages:
      - gcc-4.8
      - g++-4.8
      - clang-3.8
      - lldb-3.8
      - zsh
      - ksh
cache:
  directories:
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/.cache
before_install:
  - $SHELL --version 2> /dev/null || dpkg -s $SHELL 2> /dev/null || which $SHELL
  - curl --version
  - wget --version
  - clang --version
  - clang++ --version
  - if [ -n "${SHELLCHECK-}" ]; then stack setup && stack install ShellCheck && shellcheck --version ; fi
  - if [ -z "${SHELLCHECK-}" ]; then sudo ln -sf /usr/bin/clang-3.8 /usr/bin/clang && sudo ln -sf /usr/bin/clang++-3.8 /usr/bin/clang++ && clang --version ; fi
install:
  - (mkdir /tmp/urchin && cd /tmp/urchin && curl -s "$(curl -s https://registry.npmjs.com/urchin | grep -Eo '"tarball":\s*"[^"]+"' | tail -n 1 | awk -F\" '{ print $4 }')" -O && tar -x -f urchin*)
  - chmod +x /tmp/urchin/package/urchin
  - '[ -z "$WITHOUT_CURL" ] || sudo apt-get remove curl -y'
script:
  - if [ -n "${SHELLCHECK-}" ]; then shellcheck -s bash nvm.sh && shellcheck -s sh nvm.sh && shellcheck -s dash nvm.sh && shellcheck -s ksh nvm.sh && shellcheck -s bash install.sh ; fi
  - if [ -z "${SHELLCHECK-}" ]; then make TEST_SUITE=$TEST_SUITE URCHIN=/tmp/urchin/package/urchin test-$SHELL ; fi
env:
  global:
    - CXX=g++-4.8
    - CC=gcc-4.8
    - PATH=$(echo $PATH | sed 's/::/:/')
    - NVM_DIR="${TRAVIS_BUILD_DIR}"
  matrix:
    - SHELLCHECK=true
      apt:
        sources:
          - fpcomplete-precise
        packages:
          - stack
          - bc
    - SHELL=bash TEST_SUITE=install_script
